#!/bin/sh

mkdir includes/attachments
chmod 777 includes/attachments
chmod -R 755 www/images
chmod 755 www/javascript.js
chmod 755 www/styles.php

cp install/configVars.php.default includes/configVars.php
cp install/header.php.default www/header.php
