#!/usr/bin/sh

chmod 777 includes/attachments
chmod -R 755 www/images
chmod 755 www/javascript.js
chmod 755 www/styles.php

cp installs/configVars.php.default includes/configVars.php
cp installs/header.php.default www/header.php
