#!/bin/sh

mkdir includes/attachments
mkdir includes/logs
mkdir includes/cache
chmod 777 includes/attachments
chmod 777 includes/logs
chmod 777 includes/cache
chmod -R 755 www/images
chmod 755 www/javascript.js
chmod 755 www/styles.php

cp install/configVars.php.default includes/configVars.php
cp install/header.php.default www/header.php
cp install/egate_config.php.default includes/egate_config.php