
DROP TABLE ZENTRACK_PREFERENCES;

CREATE TABLE ZENTRACK_PREFERENCES (
  user_id number(12) DEFAULT 0,
  prefname varchar2(25) default NULL,
  prefval  varchar2(50) default NULL
) ;

CREATE INDEX USERPREF_USER ON ZENTRACK_PREFERENCES (user_id);